name: game_stuff
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  calc: 0.2.1
  flutter:
    sdk: flutter
  flame: ^1.17.0
  gap: ^3.0.1
  infinite_listview: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
